SELECT
	CUSTOMERID ,
	FIRSTNAME ,
	LASTNAME ,
	EMAIL ,
	PHONE ,
	ADDRESS ,
	CITY ,
	STATE ,
	ZIPCODE ,
	UPDATED_AT ?
    CONCAT (FIRSTNAME,' ', LASTNAME) as  CUSTOMERNAME
FROM 
    L1_LANDING.CUSTOMERS